apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: us.gcr.io/nouran-gcp-348610/gcp-python-app:v1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: configMap 