apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: python
  template:
    metadata:
      labels:
        backend: python
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: python
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        envFrom:
        - configMapRef:
            name: redis-env
      - name: node
        image: {{ .Values.nodeIimage.repository }}:{{ .Values.nodeIimage.tag }}
        envFrom:
        - configMapRef:
            name: redis-env
      - name: redis
        image: {{ .Values.memcachedImage.registry }}/{{ .Values.memcachedImage.repository }}:{{ .Values.memcachedImage.tag }}
        envFrom:
        - configMapRef:
            name: redis-env
    
