apiVersion: v1
kind: Service
metadata:
  name: nodeport-frontend
  labels:
    service: nodeport
spec:
  type: {{ .Values.service.type }}
  ports:
{{- with .Values.service }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      nodePort: {{ .nodePort }}
{{- end }}
      protocol: TCP
      name: http
  selector:
    backend: python
